

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: dotnet-api
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - mysql-network

volumes:
  mysql_data:

networks:
  mysql-network:
    driver: bridge
